GoogleCloudPlatform/nodejs-getting-started

lib/images.js
This changes the public URL for a file in GCS to a safer alternative. Bucket names are allowed to hold `.` characters, which would result in an incorrect URL. We recently ran into this with gcloud: https://github.com/GoogleCloudPlatform/gcloud-node/pull/638.
I'll be sending 2 more PRs for the other branches as well.
=> use path format for public URL

books/model-mongodb.js
This avoids having to open a new mongo connection each time. The system quickly
runs out of resources if too many mongo connections are open at the same time.
This is probably needed on almost all the branches.
=> Cache mongo collection

app.yaml
This is a temporary work-around for a bug in the Cloud SDK [1], where the
node_modules directory is uploaded. Until this bug is fixed, this bug will
ensure that the 1-hello-world example deploys successfully.
Due to the bug in question, the node_modules directory was being uploaded. This
causes issues with the Docker build on Windows, and causes increased build times
in general.
[1] https://code.google.com/p/google-cloud-sdk/issues/detail?id=210
=> Add skip_files entry to app.yaml

gce/deploy.sh
The `--group` flag changed to `--instance-group` in a recent build. The `--group` flag seems to work still, but `--instance-group` is preferable.
=> Update `backend-services add-backend` syntax

.kokoro/e2e-tests/build.sh
We need Node 8 as specified in the package.json.
=> Update Node version in Kokoro tests

.kokoro/e2e-tests/mongodb/6_pubsub.cfg
https://github.com/GoogleCloudPlatform/nodejs-getting-started/pull/155/files
deleted `model-mongodb.js`. This PR removes the test that is now
obsolete.
=> Delete obsolete test

2-structured-data/app.yaml, 3-binary-data/app.yaml, 4-auth/app.yaml, 5-logging/app.yaml, 6-pubsub/app.yaml
Pub/Sub tests were failing due to OOM errors. This PR switches to `f2` instances (from the default `f1`s) to increase the amount of memory available.
=> Fix flaky test failures due to OOMs

4-auth/lib/oauth2.js, 5-logging/lib/oauth2.js, 6-pubsub/lib/oauth2.js, 7-gce/lib/oauth2.js, optional-kubernetes-engine/lib/oauth2.js
Passport.js uses Google+ as default for the Google Strategy. Use oauth `userinfo` instead.
=> Use oauth userinfo instead of Google+ profile

7-gce/gce/deploy.sh, 7-gce/gce/teardown.sh
Update debian image. Fix some options that are deprecated. Use a larger
instance. This is needed for the startup script to work.
Fixes https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues/280
=> (fix): update deploy.sh script

.kokoro/e2e-tests/build.sh, 2-structured-data/test/_test-config.js, 3-binary-data/test/_test-config.js, 4-auth/test/_test-config.js, 5-logging/test/_test-config.js, 6-pubsub/test/_test-config.js, 7-gce/test/_test-config.js
e2e tests send request against the live app living at
`https://${opts.version}-dot-${opts.project}.appspot.com`;
The test config relies on `opts.project`, which we configure via
an environment variable.
Note that only our tests use $GCLOUD_PROJECT, it is not used in the app.
=> Fix e2e tests

.gitignore, 1-hello-world/package.json, authenticating-users/package.json, background/README.md, background/function/package.json, background/function/translate.js, background/server/app.js, background/server/app.yaml, background/server/index.html, background/server/main.js, background/server/package.json, bookshelf/package.json, package.json, sessions/package.json
Add code for background processing with PubSub and Firestore. 
Drive-by fix: clean up `package.json` files.
Tests are failing as we're still testing the old bookshelf config on the wrong branch.
=> Add background tutorial

authenticating-users/app.js
Drive-by fix: Use camel case for variables.
=> Use async/await in authenticating-users

README.md
The example folders' links were outdated due to different branch's name.
=> Update example folders' links

sessions/index.js
The Collection (kind) must be configured in the StoreOptions of the FirestoreStore and not in the settings of the Firestore.
https://github.com/googleapis/nodejs-firestore-session#using-the-client-library
=> fix firestore session config example issue

gce/test/app.test.js
Closes #450, adds logging
I'm trying not to add a try-catch block because I don't think that would preserve the intended functionality of the test. But, will add logging, and see if this doesn't help.
In local tests, the before hook was taking 108s, just a few longer than the timeout. Hopefully this fix addresses that.
=> fix: increase timeout, add logging

.kokoro/build.sh
See #485 
The script should fail when it tries activating the credentials and never even start running the tests.
=> build: build.sh should fail early if any command fails

gce/startup-script.sh
Updates the GCE sample app to use Node.js v16.15.0. Currently it uses
v8.12.0, which is no longer supported.
Fixes #541
=> Update GCE sample to Node.js v16.15.0

ci/cloudbuild/run_test.sh
The btlr binary is built by the following command:
$ env GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -v -a
From this commit:
https://github.com/googleapis/btlr/tree/1640a1a8373d6cdbcc9b5413a55f3e991de59359
fixes #535
=> testing: run tests in parallel

ci/cloudbuild/run_test.sh
=> fix: fixes the test driver when there's no change

ci/cloudbuild/Dockerfile, ci/cloudbuild/run_test.sh
=> testing: remove btlr binary
