GoogleCloudPlatform/nodejs-getting-started

1-hello-world/package.json, 2-structured-data/books/model-datastore.js, 2-structured-data/package.json, 3-binary-data/books/model-datastore.js, 3-binary-data/config.js, 3-binary-data/package.json, 4-auth/books/model-datastore.js, 4-auth/config.js, 4-auth/package.json, 5-logging/books/model-datastore.js, 5-logging/config.js, 5-logging/package.json, 6-pubsub/books/model-datastore.js, 6-pubsub/config.js, 6-pubsub/package.json, 7-gce/books/model-datastore.js, 7-gce/config.js, 7-gce/package.json
Additionally, updating dependencies (notably gcloud-node).
=> Fixing datastore pagination issue

2-structured-data/app.js, 2-structured-data/books/api.js, 2-structured-data/books/crud.js, 3-binary-data/app.js, 3-binary-data/books/api.js, 3-binary-data/books/crud.js, 4-auth/app.js, 4-auth/books/api.js, 4-auth/books/crud.js, 5-logging/app.js, 5-logging/books/api.js, 5-logging/books/crud.js, 6-pubsub/app.js, 6-pubsub/books/api.js, 6-pubsub/books/crud.js, 7-gce/app.js, 7-gce/books/api.js, 7-gce/books/crud.js
Cleaned up some code style and added some comments.
=> Fixes #38 so errors will be logged properly. 

3-binary-data/lib/images.js
Gets the Content-Type from multer and sets it when uploading the
image.
Fixes #66
=> Set the Content-Type of uploaded images

4-auth/config.js, 5-logging/config.js, 6-pubsub/config.js, 7-gce/config.js
=> Fix issue with MEMCACHE_URL (#61)

4-auth/lib/images.js, 5-logging/lib/images.js, 6-pubsub/lib/images.js, 7-gce/lib/images.js
As title.
Since this change was pretty robotic, **I did not test it locally** - though I'd be happy to if someone wants me to.
=> Fix content-type

4-auth/books/model-datastore.js, 5-logging/books/model-datastore.js, 6-pubsub/books/model-datastore.js, 7-gce/books/model-datastore.js, optional-container-engine/books/model-datastore.js
Fixes #59.
@jonparrott @jmdobry Should be good to review.
=> Fix model-datastore filter

2-structured-data/books/model-datastore.js, 2-structured-data/package.json, 3-binary-data/books/model-datastore.js, 3-binary-data/package.json, 4-auth/books/model-datastore.js, 4-auth/package.json, 5-logging/books/model-datastore.js, 5-logging/package.json, 6-pubsub/books/model-datastore.js, 6-pubsub/package.json, 7-gce/books/model-datastore.js, 7-gce/package.json, optional-container-engine/books/model-datastore.js, optional-container-engine/package.json
Fixes #57 
@jonparrott @jmdobry Care to review?
=> Fix hasMore not fetching datastore cursor

.gitignore, 1-hello-world/app.yaml, 2-structured-data/app.yaml, 2-structured-data/books/model-cloudsql.js, 2-structured-data/config.js, 2-structured-data/test/app.test.js, 3-binary-data/app.yaml, 3-binary-data/books/model-cloudsql.js, 3-binary-data/config.js, 3-binary-data/test/app.test.js, 4-auth/app.yaml, 4-auth/books/model-cloudsql.js, 4-auth/config.js, 4-auth/test/app.test.js, 5-logging/app.yaml, 5-logging/books/model-cloudsql.js, 5-logging/config.js, 5-logging/test/app.test.js, 6-pubsub/app.yaml, 6-pubsub/books/model-cloudsql.js, 6-pubsub/config.js, 6-pubsub/test/app.test.js, 7-gce/app.yaml, 7-gce/books/model-cloudsql.js, 7-gce/config.js, 7-gce/test/app.test.js, optional-container-engine/books/model-cloudsql.js, optional-container-engine/config.js, optional-container-engine/test/app.test.js
=> Port bookshelf to env:flex and Cloud SQL v2

7-gce/gce/deploy.sh
Context: https://github.com/GoogleCloudPlatform/golang-samples/pull/205
=> Fix gcloud commands for GCE deployment

3-binary-data/lib/images.js, 4-auth/lib/images.js, 5-logging/app.js, 5-logging/lib/images.js, 6-pubsub/app.js, 6-pubsub/lib/images.js, 6-pubsub/test/worker.test.js, 6-pubsub/worker.js, 7-gce/app.js, 7-gce/lib/images.js, 7-gce/test/worker.test.js, 7-gce/worker.js, optional-container-engine/app.js, optional-container-engine/lib/images.js, optional-container-engine/test/worker.test.js, optional-container-engine/worker.js, package.json
=> Update libraries + make images public

.travis.yml, 5-logging/lib/logging.js, 5-logging/package.json, 6-pubsub/lib/logging.js, 6-pubsub/package.json, 7-gce/lib/logging.js, 7-gce/package.json, optional-container-engine/lib/logging.js, optional-container-engine/package.json
=> Update logging to use @google-cloud/logging-winston

1-hello-world/package.json, 1-hello-world/yarn.lock, 2-structured-data/package.json, 2-structured-data/yarn.lock, 3-binary-data/package.json, 3-binary-data/yarn.lock, 4-auth/package.json, 4-auth/yarn.lock, 5-logging/package.json, 5-logging/yarn.lock, 6-pubsub/package.json, 6-pubsub/yarn.lock, 7-gce/package.json, 7-gce/yarn.lock, optional-container-engine/package.json, optional-container-engine/yarn.lock, package.json, yarn.lock
These were inconsistent, and the dependency unification script was causing the root `package.json` to be out of date.
=> Update subfolder package.json files

optional-kubernetes-engine/bookshelf-frontend-datastore.yaml, optional-kubernetes-engine/bookshelf-frontend-mongodb.yaml, optional-kubernetes-engine/bookshelf-worker-datastore.yaml, optional-kubernetes-engine/bookshelf-worker-mongodb.yaml
=> Remove GOOGLE_APPLICATION_CREDENTIALS secret from non-SQL K8s tutorials

.kokoro/e2e_tests_docker.sh
@ahmetb - is 2 minutes (120 seconds) enough wait time, or should I increase this?
=> Kokoro: add delay between service and cluster deletions

2-structured-data/books/crud.js, 3-binary-data/books/crud.js, 4-auth/books/crud.js, 5-logging/books/crud.js, 6-pubsub/books/crud.js, 7-gce/books/crud.js, optional-kubernetes-engine/books/crud.js
Clone of #127 without the git screwup.
Already approved by @jmdobry - merging as-is.
=> Fix typo, take 2

.kokoro/common.cfg, .kokoro/e2e_tests-1_hello_world.cfg, .kokoro/e2e_tests-2_structured_data-datastore.cfg, .kokoro/e2e_tests-2_structured_data-mongodb.cfg, .kokoro/e2e_tests-2_structured_data-sql.cfg, .kokoro/e2e_tests-3_binary_data-datastore.cfg, .kokoro/e2e_tests-3_binary_data-mongodb.cfg, .kokoro/e2e_tests-3_binary_data-sql.cfg, .kokoro/e2e_tests-4_auth-datastore.cfg, .kokoro/e2e_tests-4_auth-mongodb.cfg, .kokoro/e2e_tests-4_auth-sql.cfg, .kokoro/e2e_tests-5_logging-datastore.cfg, .kokoro/e2e_tests-5_logging-mongodb.cfg, .kokoro/e2e_tests-5_logging-sql.cfg, .kokoro/e2e_tests-6_pubsub-datastore.cfg, .kokoro/e2e_tests-6_pubsub-mongodb.cfg, .kokoro/e2e_tests-6_pubsub-sql.cfg, .kokoro/e2e_tests-7_gce-datastore.cfg, .kokoro/e2e_tests-7_gce-mongodb.cfg, .kokoro/e2e_tests-7_gce-sql.cfg, .kokoro/e2e_tests-optional_container_engine-datastore.cfg, .kokoro/e2e_tests-optional_container_engine-mongodb.cfg, .kokoro/e2e_tests-optional_container_engine-sql.cfg, .kokoro/system_tests-cloudsql.cfg, .kokoro/system_tests-datastore.cfg, .kokoro/system_tests-mongodb.cfg
Move the definition of gfile_resources to the common config file as
it is the same for all build configs.
=> Simplify Kokoro configs

.kokoro/e2e-tests/build.sh
`app.yaml` is already in the folder and configured for standard.
=> Delete flex config

2-structured-data/app.yaml, 4-auth/app.yaml, 5-logging/app.yaml, 6-pubsub/app.yaml
the value is the actual default value.
=> Remove handlers section

6-pubsub/lib/background.js, 6-pubsub/package.json, 6-pubsub/test/background.test.js, 7-gce/lib/background.js, 7-gce/package.json, 7-gce/test/background.test.js, optional-kubernetes-engine/lib/background.js, optional-kubernetes-engine/package.json, optional-kubernetes-engine/test/background.test.js, package.json
Fixes https://github.com/GoogleCloudPlatform/nodejs-getting-started/pull/241
=> fix(deps): update dependency @google-cloud/pubsub to v0.21.0

package.json
Tests got deactivated in
https://github.com/GoogleCloudPlatform/nodejs-getting-started/pull/168
=> Activate datastore tests

7-gce/README.md, optional-kubernetes-engine/README.md
=> Remove MongoDB badge

7-gce/README.md, optional-kubernetes-engine/README.md
This reverts commit 30d625750f542a03e9c239ac851560ac0def3080.
=> Revert "Remove MongoDB badge (#302)"

sessions/index.js, sessions/package.json
Drive-by fix: Add start script to package.json.
Fixes https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues/331
=> Replace 5 with greetings.length

authenticating-users/package.json, bookshelf/README.md, bookshelf/app.js, bookshelf/books/api.js, bookshelf/books/crud.js, bookshelf/books/firestore.js, bookshelf/lib/images.js
Drive-by fix: Add Readme to bookshelf.
=> Use async/await and simplify error handling

sessions/index.js
Correcting this back to greetings. Must have been a poor force push that overwrote it.
=> Use greetings instead of colors in sessions tutorial

authenticating-users/app.js, sessions/app.yaml
Drive-by fix: Run linter on auth directory.
=> Fix app.yaml in sessions

README.md
Fixes: https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues/362
=> Updat Readme

bookshelf/lib/images.js
Update usage of `@google-cloud/storage` after breaking #393
=> fix: update usage of @google-cloud/storage

authenticating-users/app.js, authenticating-users/package.json, package.json
=> update authenticate-users sample with new ID token methods

authenticating-users/test/app.test.js
Reverts GoogleCloudPlatform/nodejs-getting-started#412
=> Revert "chore: test buildcop - should open an issue "

background/package.json, background/test/app.test.js
=> fix: flaky background test

authenticating-users/app.js, authenticating-users/test/app.test.js, background/function/translate.js, background/server/app.js, background/test/app.test.js, background/test/testApp/translate.js, bookshelf/books/firestore.js, bookshelf/lib/images.js, bookshelf/test/app.test.js, gce/app.js, gce/test/app.test.js, package.json, sessions/test/index.test.js
Replaces https://github.com/GoogleCloudPlatform/nodejs-getting-started/pull/421
=> chore(deps): update dependency prettier to v2

gce/test/app.test.js
This addition to the system test skips the actual test function if the response is timing out.
Solves #448
=> build: add skip function when test is going to time out

background/test/app.test.js
Pull standup logic into helper so that it can be run before each test case add retries and exponential backoff.
Fixes #491
Fixes #490
=> test(background): make tests independent

gce/test/app.test.js
=> fix: bump test timeouts

ci/cloudbuild/run_test.sh
=> build: use absolute path and add some debug outputs

ci/cloudbuild/run_single_test.sh, ci/cloudbuild/run_test.sh
to eliminate the possibility of something deleting the binary inside the workdir
=> build: download flakybot outside of the workdir

ci/cloudbuild/Dockerfile, ci/cloudbuild/run_single_test.sh, ci/cloudbuild/run_test.sh
=> build: build flakybot in the Dockerfile

authenticating-users/test/app.test.js, ci/cloudbuild/run_single_test.sh
to test flakybot for reporting failure
=> chore: intentionally fail in continuous build

authenticating-users/test/app.test.js
=> fix: remove failing test

background/test/app.test.js
=> fix(background): increased the timeout for the test

background/test/app.test.js, package.json
also reusing the service between tests.
fixes #527
=> build: clean up old leaked Cloud Functions

background/package.json, package.json
We need to add "@google-cloud/functions" to package.json in background
directory.
fixes #532
=> fix(background): fix broken build

ci/cloudbuild/create_build_triggers.sh, ci/cloudbuild/export/gcb-continuous-node14.yaml, ci/cloudbuild/export/gcb-nightly-node14.yaml, ci/cloudbuild/export/gcb-presubmit-node14.yaml, ci/cloudbuild/export_triggers.sh, ci/cloudbuild/import_triggers.sh
also added a script for exporting the current triggers.
=> chore: update scripts for creating triggers

bookshelf/Dockerfile
Add Dockerfile to support container deployments of bookshelf app.
=> build: add Dockerfile to bookshelf

gce/test/app.test.js
=> build: update image family for test

gce/startup-script.sh
b/411514977
minimal changes to resolve usability issues. 
updated to add error handling
=> fix: update to modern Node.js and remove source repos
